### ISSUE TITLE
Any way to change cipher for connection

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#102]
I noticed all my ASR's fail to connect. I am getting this message back in the logs

                            KeyExchangeFailed: No matching encryption algorithm found, sent
                             chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr and received
                             aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc

**Comment by checktheroads** [comment]
The ciphers used should conform to whatever the server supports. IOS-XE & IOS-XR use the [Scrapli](https://github.com/carlmontanari/scrapli) driver under the hood, from their docs:

> ### Known Issues 
- Not an "issue" necessarily, but many users end up having kex/cipher negotiation issues -- this is easily fixed by setting up your ssh config file to have the appropriate settings [...]

Meaning, you should see the same result if you just SSH to the router from the server via the console, so you'd need to update your ssh config accordingly. Let me know if that makes sense, or if this doesn't work.

Thanks,
Matt
