### ISSUE TITLE
Unexpected Keyboard Interupt

### ISSUE THREAD

**Issue by YuetAu** [checktheroads/hyperglass#116]
# Bug Description

The program exit on its own without click Ctrl + C.

# Expected behavior

Keep running

# Steps to Reproduce

`hyperglass start`
https://gist.github.com/YuetAu/416e0522bd70d798649e220f7795fbb4

## Local Configurations

[`hyperglass.yaml`](https://gist.github.com/YuetAu/1542c5d90db3bf5a7eaf86c1d58eb637)
[`devices.yaml`](https://gist.github.com/YuetAu/cd8e38e07286fc8b28a9de98cf96a920)
`commands.yaml` is blank

## Logs

https://gist.github.com/YuetAu/416e0522bd70d798649e220f7795fbb4

# Possible Solution

I have tried edit the code and found out it exited because of SystemExit instead of KeyboardInterupt. But I can't extract why or which bit of code causes the error.

# Environment

## Server

| Metric | Value |
| ------ | ----- |
| **hyperglass Version** | **1.0.0-beta.76** |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.6.8` |
| **Platform Info** | `Linux-5.10.13-1.el7.elrepo.x86_64-x86_64-with-centos-7.9.2009-Core` |
| **CPU Info** | Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz |
| **Logical Cores** | `8` |
| **Physical Cores** | `8` |
| **Processor Speed** | 2.9GHz |
| **Total Memory** | 6.23 GB |
| **Memory Utilization** | 89.6% |
| **Total Disk Space** | 102.69 GB |
| **Disk Utilization** | 23.1% |

**Comment by MrFloffy** [comment]
I had this problem, i fix it rebooting the machine. I don't know what causes it, but i think maybe be an error with multiple active sessions.

**Comment by checktheroads** [comment]
Hey there,

I'm not sure I fully understand the issue - are you saying you get the `Stopping hyperglass due to keyboard interrupt.` error out of nowhere, even if you did not issue a keyboard interrupt (e.g. <kbd>Ctrl</kbd><kbd>C</kbd>)? If so, that's quite strange. The only thing I can think of is that Gunicorn does raise a `SystemExit` exception when it encounters an error.

I'm working on a beta.77 release tonight to address some random bugs, I'm throwing in an extra logging statement to print the exception raised during `hyperglass start` before re-raising. Once it's up, give that a try and see if you get any more information about the cause.

**Comment by YuetAu** [comment]
Yes, the problem is as mention and rebooting fix the problem. I am sorry I didn't do that before submitting a bug report.
