### ISSUE TITLE
[Bug] Cisco parser views for hyperglass user not working with v1.0.0-beta.78

### ISSUE THREAD

**Issue by schadom** [checktheroads/hyperglass#120]
Hello,

it seems that parser views for locking-down the hyperglass user on Cisco IOS-XE are currently not working with the latest hyperglass beta.  I configured the looking glass user according to https://hyperglass.readthedocs.io/en/latest/extras/securing-router-access/ like the following:

	username hyperglass privilege 15 view looking-glass secret 9 xxx
	!
	parser view looking-glass
	 secret 9 xxx
	 commands exec include all traceroute
	 commands exec include all ping
	 commands exec include all terminal width
	 commands exec include all terminal length
	 commands exec include terminal
	 commands exec include all show bgp
	 commands exec include show
	!
	 
	 
From the hyperglass logs:

	[INFO] 20210216 22:55:20 | scrapli.driver.async_driver:100 | open → Opening connection to router1.evilcorp.local
	[INFO] 20210216 22:55:20 | scrapli.driver.base_network_driver:318 | _pre_acquire_priv → Attempting to acquire `privilege_exec` privilege level
	[INFO] 20210216 22:55:20 | scrapli.driver.base_network_driver:389 | _process_acquire_priv → Attempting to escalate from exec to privilege_exec
	[CRITICAL] 20210216 22:55:49 | hyperglass.exceptions:40 | __init__ → [DANGER] Error connecting to router1.evilcorp.local: Request timed out.
	/usr/local/lib/python3.8/dist-packages/scrapli/driver/base_network_driver.py:300: UserWarning: 
	***** Privilege escalation generally requires an `auth_secondary` password, but none is set! 
	scrapli will try to escalate privilege without entering a password but may fail.
	Set an `auth_secondary` password if your device requires a password to increase privilege, otherwise ignore this message.
	***** Privilege escalation generally requires an `auth_secondary` password, but none is set! 
	  warnings.warn(warning)
	Exception in callback Loop._read_from_self
	handle: <Handle Loop._read_from_self>
	Traceback (most recent call last):
	  File "uvloop/cbhandles.pyx", line 73, in uvloop.loop.Handle._run
	  File "uvloop/loop.pyx", line 359, in uvloop.loop.Loop._read_from_self
	  File "uvloop/loop.pyx", line 364, in uvloop.loop.Loop._invoke_signals
	  File "uvloop/loop.pyx", line 339, in uvloop.loop.Loop._ceval_process_signals
	  File "/usr/local/lib/python3.8/dist-packages/hyperglass/execution/main.py", line 34, in handler
	    raise DeviceTimeout(**exc_args)
	hyperglass.exceptions.DeviceTimeout: Error connecting to router1.evilcorp.local: Request timed out.
	[ERROR] 20210216 22:55:50 | hyperglass.execution.drivers.ssh_scrapli:126 | collect → Timed out sending input to device.
	[CRITICAL] 20210216 22:55:50 | hyperglass.exceptions:40 | __init__ → [DANGER] Error connecting to None: Request timed out.
	

After removing the parser view from the user it works as expected. 
Why hyperglass needs to escalate privileges anyways?

Thanks

**Comment by checktheroads** [comment]
Just as an FYI, the docs you linked are for the original or v0 version of hyperglass - _not_ the beta. I'm still leaving those docs up (with a warning), since v0 is still technically available. That being said, the parser view config is still correct and works just fine for me on a production Cisco IOS-XE router in my organization. This is directly off my router, secrets excluded:

```
username lg privilege 15 view lg secret <secret>

parser view lg
 secret <secret>
 commands exec include all traceroute
 commands exec include all ping
 commands exec include all terminal width
 commands exec include all terminal length
 commands exec include terminal
 commands exec include all show bgp
 commands exec include show
```

It looks like your router requires an enable password - this may be a key difference between your router and mine. The best way to test/verify this would be to log in to the router as the hyperglass user (with the parser view enabled) and try to run the commands manually. For Cisco IOS, see [here](https://github.com/checktheroads/hyperglass/blob/v1.0.0/hyperglass/models/commands/cisco_ios.py) for the defaults.

I, personally, find requiring an enable password to be obtuse, and so generally my AAA config for local auth is something like:

```
aaa new-model
aaa authentication login default local
aaa authentication enable default enable
aaa authorization console
aaa authorization exec default local
```

The result is that any user logging in is at an exec prompt, not an enable prompt. Then, to lock down any accounts, the parser-view works perfectly. That may or may not be "correct", and may or may not fit your org's security policies, but it's worked for me for many years.

All of that said, I could add the ability to specify an enable password (which would map to the `auth_secondary` password Scrapli is referring to in your log output), if it's really necessary. I will throw out there - hyperglass has been available one way or another for nearly 2 years and this is the first time it's come up :) But, if it's needed, I can add it.

**Comment by schadom** [comment]
Thank you very much @checktheroads for the detailed response! I can confirm that after disabling the `enable password` it works as expected. I've just adapted your AAA config and this works fine. 

Thank you again very much - also for developing this awesome tool!
