### ISSUE TITLE
Add an option for downloading test files

### ISSUE THREAD

**Issue by potvinp** [checktheroads/hyperglass#134]
# Feature Description

Add an option for downloading test files with sizes of 10MB, 100MB, 1GB and 10GB (similar to what other looking glass platforms have). Having this option built into hyperglass can make this a top contender in available looking glass platforms that has all of the features that one could want from a looking glass platform.

**Comment by cameront-1** [comment]
If this is done it will need to be considered for networks with multiple/many pops. Should not be a part of the hyperglass server.

**Comment by pcfriek1987** [comment]
In my opinion, download files have nothing to do with a looking glass even if other platforms do it, those would be for a speedtest page or a mirror server. 

You can reference to such a page on the looking glass sure, but it shouldn't be added just because everyone has it, the whole reason most people use Hyperglass is because it does things different then the rest.

**Comment by checktheroads** [comment]
I think this is out of scope for hyperglass. I never intended it to be a speed test app, and I think the intent of looking glass users is more directed towards route optimization and verifying reachability rather than measuring performance.
