### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by TomHetmer** [checktheroads/hyperglass#18]
A docker container on hub.docker.com would be nice for easier setup!

**Comment by checktheroads** [comment]
Hi Tom,

Believe it or not, this was Issue #1! Unfortunately I don’t have a ton of docker experience (yet), so I don’t currently have the expertise to knock this out quickly. If you have the skill set and are willing to contribute, I’d be happy to test and approve a PR, though. Otherwise, I’ll have to backburner this for the time being, in favor of features and docs.

**Comment by checktheroads** [comment]
Closing this for now - I welcome any PRs for dockerizing hyperglass but probably will not do this myself for quite a while.
