### ISSUE TITLE
Allow querying for domain names

### ISSUE THREAD

**Issue by TomHetmer** [checktheroads/hyperglass#19]
Basically, like this

```
        # TH's domain resolver method
        regex = r"\b((?=[a-z0-9-]{1,63}\.)(xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,63}\b"
       	if re.match(regex, self.input_target):
                try:
                       	data = socket.gethostbyname(self.input_target)
                       	self.input_target = str(data)
                except Exception:
                       	pass
        # TH's domain resolver method end
```
This doesn't work with geo DNS and many locations well but should be good enough for basic use cases.

**Comment by checktheroads** [comment]
Hi Tom,

This is on the roadmap, but it’s a lower priority item at the moment. My main priority right now is finishing up the v1 release, after which I do want to circle back to this. I don’t think I’ll be implementing hostname queries quite the way you describe, as I have something else in mind. For one, I don’t think I want to do the DNS query from hyperglass, because of what you mentioned about geo DNS (GSLB most likely). I wouldn’t want someone to put in a Ping query for www.google.com, have hyperglass resolve the A/AAAA record and send the query to the router as is, as this would be an inaccurate representation of the target router’s view or connectivity to the host.

So, this means the DNS lookup would happen on the router, which means it needs to be configurable per router (for enable/disable if the operator doesn’t want to support DNS, or if the router isn’t configured as such). Additionally, with the upcoming addition of VRF support, we’d need to be able to enable/disable DNS support per-VRF, as I can easily see someone having DNS configured on their default table, but no DNS on a customer VRF. On the flip side, I could see needing both, in cases where hyperglass is used as an internal tool. So, it’ll be a little bit of work to get that rolling, but not too bad actually.

Another thing I’d like to do with DNS is do a PTR lookup on a query target and present it in the UI in a pretty way, and I think this would require the use of a DNS library (I have a couple starred I think).

Anyway, I’ll be keeping this issue open until I get this done. Thanks!

**Comment by checktheroads** [comment]
I'm pleased to be able to close this out, as this feature has been added to the [v1.0.0 beta release](https://github.com/checktheroads/hyperglass/tree/v1.0.0).

FYI - the way I ended up implementing this was by doing a DNS over HTTPS query for the query target value in the form, from the UI itself. While this will not use the machine's DNS stack (and as such, may resolve names differently), I thought it was the cleanest and most secure solution.

If able, give the new release a try and let me know any feedback.
Thanks!
