### ISSUE TITLE
aspath-regex Juniper

### ISSUE THREAD

**Issue by arraisfilho** [checktheroads/hyperglass#27]
Hi,

I cannot use regular expressions or any other form of query in "BGP AS Path", using Juniper.

I scanned the code and couldn't find where I can adjust it to accept expressions like ". * 1234 +".

The hyperglass accepts only the expressions contained in the help (ex: _65000 $)

Model: mx204
Junos: 18.1R3-S7.1

**Comment by checktheroads** [comment]
Hello!

Before I get too far into troubleshooting, have you tried setting [this parameter](https://hyperglass.readthedocs.io/en/latest/installation/features/#bgp-as-path)? i.e., the config would look something like this:

```toml
[features.bgp_aspath.regex]
mode = 'asplain'
asplain = '^\.\*\s\d+\s\+$'
```
The above pattern matches your example of `. * 1234 +` but might need adjusting depending on all the patterns you might want to allow.

Anyway, have you tried this and are saying it does work?

**Comment by arraisfilho** [comment]
Hello,

I already tried yes, it doesn't work, to return (. * 1234 + is an invalid AS Path).

The way it worked was by not adding parameters to the asplain, but there is no validation :/

```
[features.bgp_aspath.regex]
mode = "asplain"
asplain = ""
```

**Comment by checktheroads** [comment]
I believe in this case the single quotes are actually required. Per the [TOML docs](https://github.com/toml-lang/toml), that's how they handle string literals (similar to bash), which would be required for such a string. I don't have a Juniper device quickly accessible to test with, would you be able to see if single quotes fixes this? If not I'll see what I can rustle up.

Thanks!
-Matt

**Comment by arraisfilho** [comment]
Hi,

I tried with single quotes, but validation does not allow the use of regular expressions. If the asplain becomes expressionless and has double quotes (asplain = ""), it will work and allow any instructions.

I repeated the tests with single and double quotes, it had no effect.

**Comment by checktheroads** [comment]
Hello,

I believe I've got this one figured out. It's two things:

1: The pattern I used above (`'^\.\*\s\d+\s\+$'`) produced the same result for me. However, I changed it to `'^\.\* \d+\+$'` and hyperglass accepted it.

2: However, the produced result was still an invalid _juniper_ aspath query. This is because the default commands for `juniper` do not wrap `{target}` in quotes as JunOS requires. For example, the current default is:

```toml
[[juniper]]
[juniper.dual]
bgp_aspath = "show route protocol bgp aspath-regex {target}"
```

Which results in the command `show route protocol bgp aspath-regex .* 1234+` being sent to the router, which fails. After setting the commands in `commands.toml` to:

```toml
[[juniper]]
[juniper.dual]
bgp_aspath = 'show route protocol bgp aspath-regex "{target}"'
```

I'm able to successfully query the router with this pattern. I'm going to push a quick change to the default commands which should resolve this. 

Thanks!
