### ISSUE TITLE
bgp lookup on /32's fail

### ISSUE THREAD

**Issue by astlaurent** [checktheroads/hyperglass#34]
Hi

I am not sure if it is by design or a mistake but i noticed if i do a BGP lookup for a /32 (for example 4.2.2.2/32) the tool changes the mask completely. The effective command on the router becomes
show bgp ipv4 unicast 4.0.0.0/9

If it were by design i would think you would make it go to the classful boundary instead of a /9 but i would think if a mask it entered it should respect the mask

I tested on a /31 and it gets entered fine.

I know it may not be a typical use case since you would hardly ever do a BGP lookup on anything that small, I just happened to catch it in our lab where we inject fake /32 loopbacks into BGP off fake ISP's to simulate our global routing.

**Comment by checktheroads** [comment]
This is expected default behavior, and let me explain:

Some platforms don’t support BGP lookups of a host route - although from what I’ve been able to find and test, this primarily applies to IPv6, not IPv4. However, in the spirit of equality and consistency, they’re treated the same in this case.

In the “original” version, hyperglass got around this by using the `requires_ipv6_cidr` option, which threw an error if you queried, for example, `2606:4700:4700::1111` on a listed OS. Instead of throwing an error, v1, by default, does an API call to RIPEStat’s API to retrieve the _actual_ announced prefix containing that host prior to sending the query to the router. The query would be changed to `2606:4700:4700::/48`. Again, the default behavior is that this occurs for any IPv4 /32 or IPv6 /128 query. You can disable this behavior on a per device, per VRF, per address-family basis with the [`force_cidr`](https://hyperglass.io/docs/devices#ipv6) option.

**Comment by astlaurent** [comment]
thanks for the info. I don't think it will end up being a huge issue for us but i will keep it in mind if something ever comes up about it.
