### ISSUE TITLE
Online Documentation for "Adding Devices" is out of date/incomplete

### ISSUE THREAD

**Issue by linuxgemini** [checktheroads/hyperglass#55]
While setting up an instance for my BIRD router today, I have struggled to understand the documentation about "Adding Devices" because the file provided in the example configuration `hyperglass/examples/devices.yaml` is almost completely different.

- global option `proxies` are not documented
- global option `networks` are not documented
- global option `credentials` are not documented
- global option `vrfs` and how `routers` can utilize it are not documented

This also points out that the documentation on its entirety has to be reviewed for the current upstream repository.

**Comment by checktheroads** [comment]
Hi,

Sorry for the confusion with the docs. We were just discussing this in the Telegram group - I hate our docs (and I wrote them), because it’s too much mindless reference and not enough usable guide/tutorial. It’s a work in progress, and will continue to improve as I’m able to keep working on it.

Regarding your issue - those sections aren’t global options - they’re YAML aliases & anchors. I do have a comment about it at the bottom of [this page](https://hyperglass.io/docs/parameters). In a nutshell, they’re in the examples because I find it easier to maintain the config file that way, but anything other than the `routers:‘ key is 100% optional and not read by hyperglass. You _can_ add separate credential, proxy, and VRF sections for each device, or you can use the snazzy YAML aliases to reuse a set of config across multiple devices - it’s your choice.

**Comment by checktheroads** [comment]
I'm closing this issue, however I have added an offline to-do to clarify the use of YAML anchors/aliases and provide examples of how to use them if needed.
