### ISSUE TITLE
Clarify if `hyperglass build-ui` is required before the first start

### ISSUE THREAD

**Issue by bastelfreak** [checktheroads/hyperglass#79]
# Feature / Request Description

Hi! you probably noticed that I started on a Puppet module to automate the hyperglass deployment. The docs mention that it's recommended to run `hyperglass build-ui` before the service is started.

Can you clarify if it's *required* / if I should hack that into puppet? If I got the output from the service right, it builds the UI on the first startup anyways?

**Comment by checktheroads** [comment]
As it stands now, yes, it is required to run `hyperglass build-ui` during the installation. That said, that requirement is not permanent - I'm planning on adding a config flag or environment variable to disable the UI entirely for users who may want to run hyperglass headless in order to tie into their own UI. Once that's done, I'll build the `hyperglass ui` functionality into the install process itself so the user doesn't have to do it at all.

I'm leaving this open to annoy myself into implementing said feature :)

**Comment by checktheroads** [comment]
I'm going to close this issue out since the original issue/question is solved. However, I will still be decoupling the hyperglass backend from the frontend, hopefully before I (at long last) take 1.0.0 out of beta.
