### ISSUE TITLE
Clarify TLS Setup from hyperglass to hyperglass-agent in the docs

### ISSUE THREAD

**Issue by bastelfreak** [checktheroads/hyperglass#86]
# Feature Description

Hi, I want to connect my hyperglass instance to multiple hyperglass agents. It's a common pattern to bind applications to localhost and terminate TLS with a local haproxy or nginx. This is also a requirement in my environment. I bound hyperglass-agent with http to localhost and nginx terminates TLS. Now I'm wondering if hyperglass can somehow connect to this?

From my understanding of the docs, hyperglass has currently no support for using a TLS client certificate, but that's not mandatory in my environment. I'm wondering what the `cert` option is at https://hyperglass.io/docs/adding-devices#ssl . I copied the TLS certificate from nginx to hyperglass and configured that as `cert`, but hyperglass fails to initiate a TLS connection. I'm wondering if this should actually be a public key and not a certificate. I will try to test this later

However, would it be possible to support a proper PKI and validate the *certificate* from the hyperglass-agent against a root CA and/or offer a TLS client certificate?

### Is your feature request related to a problem? Please describe.

I think so. My problem is that I need to use a PKI with an inhouse CA and signed certificates.

# Environment & Use Case

# Additional Context

**Comment by bastelfreak** [comment]
@checktheroads can you take a look here and provide some guidance please?

**Comment by checktheroads** [comment]
Hey @bastelfreak, sorry about the delay. I've been slammed with work projects and haven't had much time to put into hyperglass lately, unfortunately.

Reading through your question, I have a follow-up question. Would your environment allow for standard unencrypted HTTP calls with encrypted payloads? I.e, hyperglass would symmetrically encrypt the data payload to hyperglass-agent, hyperglass-agent would decrypt it, execute, encrypt the response in the same manner, and send it back. [This is similar](https://github.com/48ix/routingpolicy/blob/master/routingpolicy/agent/main.py) to what I'm thinking (but implemented over RPC instead of HTTP).

I'm considering this because I truly hate the current way hyperglass and hyperglass-agent interact with SSL. I really want the agent to be dead simple. In the above scenario, you would still define a key on both sides, and that key would be used to encrypt/decrypt the payload. But, I don't want to "scare away" security conscious users either, so I'm curious what you think.

Thanks,
Matt

**Comment by checktheroads** [comment]
Closing this out as hyperglass-agent will be deprecated (but replaced with something similar and more generic). See #143
